// <auto-generated />
using System;
using HalalOnTheGo.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HalalOnTheGo.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240225144301_ProductsRemoveFromCategoryModel")]
    partial class ProductsRemoveFromCategoryModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HalalOnTheGo.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "food",
                            Name = "Chicken",
                            Url = "chicken"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "food",
                            Name = "Lamb",
                            Url = "meat"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "food",
                            Name = "Mutton",
                            Url = "mutton"
                        });
                });

            modelBuilder.Entity("HalalOnTheGo.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            DateCreated = new DateTime(2024, 2, 25, 14, 43, 1, 399, DateTimeKind.Local).AddTicks(6511),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Experience the epitome of freshness and quality with our HALAL whole chicken, now available for purchase on our website. Our HALAL-certified whole chickens are sourced from reputable farms, ensuring that you receive a product that aligns with your dietary preferences and cultural values. (BEST VALUE)",
                            Image = "/Images/WholeChicken.png",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 0m,
                            Price = 5.00m,
                            Title = "HALAL Whole Chicken"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            DateCreated = new DateTime(2024, 2, 25, 14, 43, 1, 399, DateTimeKind.Local).AddTicks(6562),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Indulge in the unparalleled quality and authenticity of our halal butchered chicken breasts, where tradition meets excellence. Sourced from ethically-raised, halal-certified poultry, our chicken breasts are meticulously prepared to meet the highest standards of halal butchering. Each tender and succulent piece is carefully hand-selected, ensuring a premium dining experience that aligns with your dietary preferences.",
                            Image = "/Images/chickenbreast1KG.png",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 0m,
                            Price = 4.50m,
                            Title = "HALAL Chicken Breast 1KG"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            DateCreated = new DateTime(2024, 2, 25, 14, 43, 1, 399, DateTimeKind.Local).AddTicks(6565),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Indulge in the unparalleled quality and authenticity of our halal butchered chicken breasts, where tradition meets excellence. Sourced from ethically-raised, halal-certified poultry, our chicken breasts are meticulously prepared to meet the highest standards of halal butchering. Each tender and succulent piece is carefully hand-selected, ensuring a premium dining experience that aligns with your dietary preferences.",
                            Image = "/Images/chickenbreast1KG.png",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 10.00m,
                            Price = 6.00m,
                            Title = "HALAL Chicken Breast 2KG"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            DateCreated = new DateTime(2024, 2, 25, 14, 43, 1, 399, DateTimeKind.Local).AddTicks(6567),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Indulge in the unparalleled quality and authenticity of our halal butchered chicken breasts, where tradition meets excellence. Sourced from ethically-raised, halal-certified poultry, our chicken breasts are meticulously prepared to meet the highest standards of halal butchering. Each tender and succulent piece is carefully hand-selected,ensuring a premium dining experience that aligns with your dietary preferences. OVER HALF OFF!",
                            Image = "/Images/chickenbreast1KG.png",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 37.00m,
                            Price = 15.00m,
                            Title = "HALAL Chicken Breast 5KG"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            DateCreated = new DateTime(2024, 2, 25, 14, 43, 1, 399, DateTimeKind.Local).AddTicks(6569),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Delight your senses with our premium HALAL chicken drumsticks, now available for purchase on our website. Sourced from trusted and ethical producers, our HALAL certified chicken drumsticks offer a perfect balance of quality, flavor, and convenience.",
                            Image = "/Images/Chicken-Drumsticks.png",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 0m,
                            Price = 5.00m,
                            Title = "HALAL Chicken Drumsticks (5 PIECES)"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            DateCreated = new DateTime(2024, 2, 25, 14, 43, 1, 399, DateTimeKind.Local).AddTicks(6572),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Delight your senses with our premium HALAL chicken drumsticks, now available for purchase on our website. Sourced from trusted and ethical producers, our HALAL-certified chicken drumsticks offer a perfect balance of quality, flavor, and convenience.",
                            Image = "/Images/Chicken-Drumsticks.png",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 12.15m,
                            Price = 9.95m,
                            Title = "HALAL Chicken Drumsticks (10 PIECES)"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            DateCreated = new DateTime(2024, 2, 25, 14, 43, 1, 399, DateTimeKind.Local).AddTicks(6574),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Delight your senses with our premium HALAL chicken drumsticks, now available for purchase on our website. Sourced from trusted and ethical producers, our HALAL-certified chicken drumsticks offer a perfect balance of quality, flavor, and convenience.",
                            Image = "/Images/Chicken-Drumsticks.png",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 0m,
                            Price = 14.30m,
                            Title = "HALAL Chicken Drumsticks (15 PIECES)"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            DateCreated = new DateTime(2024, 2, 25, 14, 43, 1, 399, DateTimeKind.Local).AddTicks(6576),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Discover the convenience and versatility of our halal chicken mince, now available for purchase on our website. Sourced from trusted producers and crafted with care, our halal chicken mince provides a wholesome and flavorful option for a variety of culinary creations.",
                            Image = "/Images/Chicken-Mix-Mince.png",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 7.50m,
                            Price = 5.00m,
                            Title = "HALAL Chicken Mince (Keema) 500G"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            DateCreated = new DateTime(2024, 2, 25, 14, 43, 1, 399, DateTimeKind.Local).AddTicks(6579),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Discover the convenience and versatility of our halal chicken mince, now available for purchase on our website. Sourced from trusted producers and crafted with care, our halal chicken mince provides a wholesome and flavorful option for a variety of culinary creations.",
                            Image = "/Images/Chicken-Mix-Mince.png",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 0m,
                            Price = 8.50m,
                            Title = "HALAL Chicken Mince (Keema) 2KG"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            DateCreated = new DateTime(2024, 2, 25, 14, 43, 1, 399, DateTimeKind.Local).AddTicks(6581),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Savor the exquisite taste of our Halal Butchered Lamb Chops, a culinary delight crafted with the utmost respect for halal principles. Our lamb chops are meticulously  sourced from ethically-raised, halal-certified lambs, ensuring that every succulent bite adheres to the highest standards of halal butchering. ON SALE NOW. LIMITED TIME ONLY",
                            Image = "/Images/LambChops1kg.png",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 12.60m,
                            Price = 7.00m,
                            Title = "HALAL Lamp Chops 500G"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            DateCreated = new DateTime(2024, 2, 25, 14, 43, 1, 399, DateTimeKind.Local).AddTicks(6584),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Savor the exquisite taste of our Halal Butchered Lamb Chops, a culinary delight crafted with the utmost respect for halal principles. Our lamb chops are meticulously               sourced from ethically-raised, halal-certified lambs, ensuring that every succulent bite adheres to the highest standards of halal butchering.",
                            Image = "/Images/LambChops1kg.png",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 0m,
                            Price = 13.00m,
                            Title = "HALAL Lamp Chops 1KG"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            DateCreated = new DateTime(2024, 2, 25, 14, 43, 1, 399, DateTimeKind.Local).AddTicks(6585),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Savor the exquisite taste of our Halal Butchered Lamb Chops, a culinary delight crafted with the utmost respect for halal principles. Our lamb chops are meticulously               sourced from ethically-raised, halal-certified lambs, ensuring that every succulent bite adheres to the highest standards of halal butchering.",
                            Image = "/Images/LambChops1kg.png",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 26.50m,
                            Price = 24.95m,
                            Title = "HALAL Lamp Chops 2KG"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            DateCreated = new DateTime(2024, 2, 25, 14, 43, 1, 399, DateTimeKind.Local).AddTicks(6587),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Crafted with precision and care, our HALAL lamb mince is expertly ground to perfection, ensuring a delectable texture that enhances the richness of your favorite dishes. Whether you're preparing savory kebabs, hearty casseroles, or flavorful curries, our HALAL lamb mince adds a touch of authenticity and quality to your culinary creations. ON SALE NOW - LIMITED TIME ONLY!",
                            Image = "/Images/LambMince1KG.png",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 7.00m,
                            Price = 5.00m,
                            Title = "HALAL Lamb Mince (Keema) 500G"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            DateCreated = new DateTime(2024, 2, 25, 14, 43, 1, 399, DateTimeKind.Local).AddTicks(6589),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Crafted with precision and care, our HALAL lamb mince is expertly ground to perfection, ensuring a delectable texture that enhances the richness of your favorite dishes. Whether you're preparing savory kebabs, hearty casseroles, or flavorful curries, our HALAL lamb mince adds a touch of authenticity and quality to your culinary creations.",
                            Image = "/Images/LambMince1KG.png",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 0m,
                            Price = 8.95m,
                            Title = "HALAL Lamb Mince (Keema) 2KG"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            DateCreated = new DateTime(2024, 2, 25, 14, 43, 1, 399, DateTimeKind.Local).AddTicks(6591),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Transform your meals into culinary masterpieces with the premium taste and quality of our halal lamb steaks. Order now to bring home the unparalleled richness and tenderness that only halal-certified lamb can offer. Enjoy a dining experience that combines tradition and excellence with every flavorful bite.",
                            Image = "/Images/Lamb-Leg-Steak.png",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 18.00m,
                            Price = 12.00m,
                            Title = "HALAL Lamb Steak"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            DateCreated = new DateTime(2024, 2, 25, 14, 43, 1, 399, DateTimeKind.Local).AddTicks(6593),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Elevate your culinary adventures with our premium diced with bone mutton, a tantalizing symphony of flavor and tenderness that promises to redefine your dining experience. Sourced from the finest pastures and carefully selected for its exceptional quality, our mutton is a testament to the artistry of butchery.",
                            Image = "/Images/Dice-Mutton.png",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 0m,
                            Price = 9.00m,
                            Title = "HALAL Mutton (DICED W/ BONE) 1KG"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            DateCreated = new DateTime(2024, 2, 25, 14, 43, 1, 399, DateTimeKind.Local).AddTicks(6595),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Elevate your culinary adventures with our premium diced with bone mutton, a tantalizing symphony of flavor and tenderness that promises to redefine your dining experience. Sourced from the finest pastures and carefully selected for its exceptional quality, our mutton is a testament to the artistry of butchery.",
                            Image = "/Images/Dice-Mutton.png",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 18.00m,
                            Price = 13.50m,
                            Title = "HALAL Mutton (DICED W/ BONE) 2KG"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            DateCreated = new DateTime(2024, 2, 25, 14, 43, 1, 399, DateTimeKind.Local).AddTicks(6597),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Embark on a gastronomic adventure with our exquisite mixed mutton assortment – a carefully curated blend of diverse cuts that harmonize to create a culinary masterpiece. Crafted with precision and passion, this medley of mutton promises to captivate your palate and elevate your cooking to new heights.",
                            Image = "/Images/Mixed-Mutton.png",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 11.20m,
                            Price = 7.50m,
                            Title = "HALAL Mixed Mutton 1KG"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 3,
                            DateCreated = new DateTime(2024, 2, 25, 14, 43, 1, 399, DateTimeKind.Local).AddTicks(6599),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sourced from the finest cuts of mutton, our 7-day dry-aged process is a testament to patience and precision. The result? A masterpiece that boasts an intensified, concentrated flavor profile, bringing forth the sublime fusion of richness and tenderness that can only be achieved through the art of dry aging. ON SALE NOW- LIMITED TIME ONLY! ",
                            Image = "/Images/7Day-Aged-Mutton.png",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 45.00m,
                            Price = 30.00m,
                            Title = "HALAL 7-Day Dry Aged Mutton 2KG"
                        });
                });

            modelBuilder.Entity("HalalOnTheGo.Shared.Product", b =>
                {
                    b.HasOne("HalalOnTheGo.Shared.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
